version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: papyris-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: papyris
      POSTGRES_USER: papyris_user
      POSTGRES_PASSWORD: papyris_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
